# Generated by Django 4.1.6 on 2023-02-11 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 11, 22, 52, 27, 521884)),
        ),
        migrations.AddField(
            model_name='concert',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 11, 22, 52, 27, 521895)),
        ),
    ]
