# Generated by Django 4.1.6 on 2023-02-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_concert_date_concert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
