# Generated by Django 4.1.6 on 2023-02-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_alter_concert_date_alter_concert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(default='concert.jpg', null=True, upload_to=''),
        ),
    ]
