# Generated by Django 4.1.6 on 2023-02-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0004_concert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertticket',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='concert.concert'),
        ),
    ]
