# Generated by Django 4.1.6 on 2023-02-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seattype',
            name='name',
        ),
        migrations.AddField(
            model_name='seattype',
            name='type',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('GO', 'Gold'), ('SI', 'Silver'), ('BR', 'Bronze')], default='L1', max_length=100),
        ),
    ]
